"name"= "RabbitSourceConnector",
"connector.class"= "com.github.maksimgr.RabbitSourceConnector",
"tasks.max"= "1",
"rabbitmq.host"= "localhost",
"rabbitmq.port"= "5552",
"rabbitmq.username"= "guest",
"rabbitmq.password"= "guest",
"rabbitmq.virtual.host"= "/",
"rabbitmq.queue"= "queue_name_here",
"rabbitmq.offset"= "first",
"kafka.topic"= "your_kafka_topic",
# TLS (optional)
# "rabbitmq.tls.enabled"= "true",
# "rabbitmq.tls.truststore.path"= "/path/to/truststore.jks",
# "rabbitmq.tls.truststore.password"= "changeit",

